const products = [
    {
        id: 1,
        name: 'iPhone XS',
        description: 'This is iPhone XS',
        type: 'Phone',
        capacity: '64',
        price: '500',
        image: 'images/iphone-black.jpg',
    },
    {
        id: 2,
        name: 'iPhone 12',
        description: 'This is iPhone 12',
        type: 'Phone',
        capacity: '128',
        price: '1000',
        image: 'images/iphone-green.jpg',
    },
    {
        id: 3,
        name: 'iPhone 13 Pro',
        description: 'This is iPhone 13 PRO',
        type: 'Phone',
        capacity: '256',
        price: '1500',
        image: 'images/iphone-pink.jpg',
    },
    {
        id: 4,
        name: 'iPhone 11 Pro Max',
        description: 'This is iPhone 11 PRO',
        type: 'Phone',
        capacity: '64',
        price: '1000',
        image: 'images/iphone-red.jpg',
    },
    {
        id: 5,
        name: 'iPhone X',
        description: 'This is iPhone X',
        type: 'Phone',
        capacity: '128',
        price: '2000',
        image: 'images/iphone-silver.jpg',
    },
    {
        id: 6,
        name: 'iPhone 8 plus',
        description: 'This is iPhone 8 plus',
        type: 'Phone',
        capacity: '256',
        price: '1000',
        image: 'images/iphone-white.jpg',
    },
]

export default products
